name: account_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  decimal: 2.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter_easyloading: ^3.0.5
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/aliya.jpg
    - images/setting.png
    - images/cate_icons/
    - json/